name: llm_finetune_3_10
channels:
  - defaults
  - conda-forge
  - nvidia
  - https://software.repos.intel.com/python/conda
  - https://software.repos.intel.com/python/conda/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.10.0=py310h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=25.1.0=py310h06a4308_0
  - argon2-cffi-bindings=25.1.0=py310hee96239_0
  - arrow-cpp=21.0.0=hac1acdb_1
  - asttokens=3.0.0=py310h06a4308_0
  - async-lru=2.0.5=py310h06a4308_0
  - attrs=25.4.0=py310h06a4308_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - babel=2.17.0=py310h06a4308_0
  - beautifulsoup4=4.14.3=py310h06a4308_0
  - blas=1.0=openblas
  - bleach=6.3.0=py310h06a4308_0
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotlicffi=1.2.0.0=py310h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hd44998d_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - comm=0.2.3=py310h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.4=hbda6634_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py310ha78e65c_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py310h06a4308_1
  - harfbuzz=12.3.0=h79d275a_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py310h06a4308_0
  - importlib-metadata=8.7.0=py310h06a4308_0
  - intel-openmp=2024.0.2=intel_49895
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - ipython_pygments_lexers=1.1.1=py310h06a4308_0
  - ipywidgets=8.1.7=py310h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jedi=0.19.2=py310h06a4308_0
  - joblib=1.5.3=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py310h06a4308_0
  - jsonschema=4.25.1=py310h06a4308_0
  - jsonschema-specifications=2025.9.1=py310h06a4308_0
  - jupyter=1.1.1=py310h06a4308_0
  - jupyter-lsp=2.3.0=py310h06a4308_0
  - jupyter_client=8.8.0=py310h06a4308_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.9.1=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_1
  - jupyter_server=2.17.0=py310h06a4308_1
  - jupyter_server_terminals=0.5.4=py310h06a4308_0
  - jupyterlab=4.5.3=py310h06a4308_1
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.28.0=py310h06a4308_1
  - jupyterlab_widgets=3.0.16=py310h06a4308_0
  - lame=3.100=hbd0596d_1
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.20.2=hdb19cb5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.17.0=h5579877_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.86.3=h8b17d9a_0
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libkrb5=1.22.1=h6d2bf13_0
  - libnghttp2=1.67.1=h697f920_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.31=hf7dbefb_0
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.6.1=h9f10d21_0
  - libpng=1.6.54=hee55ce4_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.21.0=h27ab2c4_0
  - libthrift=0.22.0=hd8eb582_0
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - mistune=3.1.2=py310h06a4308_0
  - mkl=2024.0.0=intel_49671
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert=7.16.6=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbconvert-pandoc=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - nomkl=3.0=0
  - notebook=7.5.3=py310h06a4308_0
  - notebook-shim=0.2.4=py310h06a4308_1
  - numexpr=2.14.1=py310ha5a4a6c_0
  - numpy-base=2.2.5=py310hf387b04_2
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.6.1=h35e630c_1
  - opentelemetry-api=1.38.0=py310h06a4308_0
  - orc=2.2.0=h372e9aa_0
  - overrides=7.7.0=py310h06a4308_0
  - packaging=25.0=py310h06a4308_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py310h06a4308_0
  - parso=0.8.5=py310h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py310h06a4308_1
  - pillow=12.1.0=py310hd9fd23a_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py310h06a4308_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pyarrow=21.0.0=py310h86c3e14_1
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.21.2=py310h06a4308_0
  - python-json-logger=4.0.0=py310h06a4308_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.3=py310h591646f_0
  - pyzmq=27.1.0=py310hcf8288c_1
  - qtconsole=5.7.0=py310h06a4308_0
  - qtpy=2.4.3=py310h06a4308_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py310h06a4308_0
  - requests=2.32.5=py310h06a4308_1
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.28.0=py310h498d7c9_0
  - s2n=1.5.14=hdbd6064_0
  - scikit-learn=1.7.2=py310h86c3e14_1
  - scipy=1.15.3=py310ha592af2_1
  - send2trash=1.8.3=py310h06a4308_0
  - setuptools=80.10.2=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - snappy=1.2.2=h4bcf44c_1
  - sniffio=1.3.1=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py310h06a4308_0
  - tbb=2021.13.0=h8d10470_4
  - terminado=0.18.1=py310h06a4308_1
  - threadpoolctl=3.5.0=py310h7040dfc_1
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=py310h06a4308_0
  - tornado=6.5.4=py310h47b2149_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.14=py310h06a4308_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - wheel=0.46.3=py310h06a4308_0
  - widgetsnbextension=4.0.14=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=py310h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.12.0+computecanada
      - aiohappyeyeballs==2.6.1+computecanada
      - aiohttp==3.12.13+computecanada
      - aiosignal==1.4.0+computecanada
      - annotated-types==0.7.0+computecanada
      - async-timeout==5.0.1+computecanada
      - bitsandbytes==0.49.0+computecanada
      - click==8.3.1+computecanada
      - curl-cffi==0.11.3+computecanada
      - datasets==4.5.0+computecanada
      - dill==0.4.0+computecanada
      - filelock==3.20.3+computecanada
      - frozendict==2.4.7
      - frozenlist==1.8.0+computecanada
      - fsspec==2025.10.0+computecanada
      - gitdb==4.0.12+computecanada
      - gitpython==3.1.46+computecanada
      - hf-xet==1.2.0+computecanada
      - huggingface-hub==1.4.1+computecanada
      - jinja2==3.1.6+computecanada
      - markupsafe==2.1.5+computecanada
      - mpmath==1.3.0+computecanada
      - multidict==6.6.0+computecanada
      - multiprocess==0.70.18+computecanada
      - multitasking==0.0.11+computecanada
      - networkx==3.4.2+computecanada
      - numpy==2.2.2+computecanada
      - pandas==2.2.3+computecanada
      - peewee==3.19.0+computecanada
      - peft==0.18.1
      - pillow-simd==9.5.0.post2+computecanada
      - propcache==0.4.1+computecanada
      - protobuf==6.33.5
      - pydantic==2.12.5+computecanada
      - pydantic-core==2.41.5
      - regex==2024.9.11+computecanada
      - safetensors==0.7.0+computecanada
      - sentry-sdk==2.52.0+computecanada
      - shellingham==1.5.4+computecanada
      - smmap==5.0.2+computecanada
      - sympy==1.13.1+computecanada
      - ta==0.11.0
      - tokenizers==0.22.2+computecanada
      - torch==2.6.0+cpu
      - torchvision==0.21.0+cpu
      - tqdm==4.67.3+computecanada
      - transformers==5.1.0
      - typer-slim==0.21.1+computecanada
      - typing-extensions==4.15.0+computecanada
      - typing-inspection==0.4.2+computecanada
      - wandb==0.24.0+computecanada
      - websockets==16.0
      - xxhash==3.5.0+computecanada
      - yarl==1.20.1+computecanada
      - yfinance==1.1.0
prefix: /home/riaarora/miniconda3/envs/llm_finetune_3_10
